#55【ロジック】タスク編集機能の実装
london-newyork/Qin_Todo_J2 pull request #74
Opened 2022-04-08 14:58 UTC by yamataso

## 概要

タスクを編集した際の挙動を修正しました。

## やったこと

TodoItem.tsx内の三項演算子に条件を追加し、タスクを編集したあとに”タスクを追加する”の文字が出ないようにしました。

## やってないこと

変更前と変更後のオブジェクトが別々に生成されている点は修正できませんでした。

2022-04-09 12:53 UTC, london-newyork requested changes
コンソールでpropsを見ると、リストを編集した時、元のIDと違っているようです。
リストを編集する時に、新たなidを取得してしまっている感じです。
例)
` { id : 01 , task: アイウエオ }　→ 編集　→  { id: 02 , task: カキクケコ }`
 のようになっていると思います。
 ammendお願いします。

2022-04-09 12:55 UTC, london-newyork commented
Changes requestedが出ていますが、修正するとき、ブランチを新しく切らなくてもこの同じPRで出していただいて大丈夫です。

2022-04-10 06:42 UTC, yamataso commented
レビューを受けた点を修正しました。
再度レビューをお願いします。

2022-04-10 09:06 UTC, london-newyork approved these changes
LGTMです。
タスクを変更しても編集前のidを引き継いでいることをコンソールで確認できました。
お疲れ様でした！

2022-04-10 09:07 UTC, london-newyork commented
[![LGTMeow](https://lgtm-images.lgtmeow.com/2022/01/20/01/c2c81c8a-75fb-442b-873f-8b7bbb11188f.webp)](https://lgtmeow.com)

2022-04-10 09:17 UTC, merged