プラスボタンをクリックすると、入力カーソルが表示されるようにする
london-newyork/Qin_Todo_J2 pull request #80
Opened 2022-04-12 12:58 UTC by geyageya

##変更の概要

登録前の入力欄のViewを、ボタンでも変えることができるようにしよう。

##画像
![スクリーンショット 2022-04-12 21 56 52](https://user-images.githubusercontent.com/74279452/162967532-18285125-f90f-4a53-b33c-285978e44d16.png)

##変更内容：

#したこと

- プラスボタンをクリックすると、「タスクを追加する」が消え、◯ボタンと点滅カーソルに切り替わるようにした。
- その後、同じボタンをもう一度、クリックすると、元に戻るようにした。

##その他したこと
・issueには記載していなかったが、完了時にタスクに横線を引くイベントは、ボタンクリックのみにした。（タスクをクリックしても、横線が引かれないようにした。）
・けんいちさんが挙動が変と指摘されていた件で、シマブーさんにも確認済み。

2022-04-13 07:36 UTC, ikk2kk reviewed
プラスボタンをクリックしても、入力カーソルが表示されていないです。
labelタグのhtmlForを使うと実現できると思います。
https://zenn.dev/kimura141899/articles/6e11e3a165460d
修正お願いします。

2022-04-13 22:04 UTC, ikk2kk approved these changes
こんなやり方があるんですね。
勉強になりました！
問題ないです。お疲れ様でした。

2022-04-14 04:37 UTC, ikk2kk reviewed
slackの内容をこちらにも記載しておきます。

https://nickel-beam-f82.notion.site/80-6a54f6713b6a4cbbb924bb5c693cb487
Notionに記載したTodayTodo変更箇所が反映されていないからだと思います。
id={"today"}
あと、Notionに記載していませんが、TodayTodoの修正と同様の修正を以下のコンポーネントにする必要があります。
TomorrowTodo.tsx => id={"tomorrow"}
SomeTimeTodo.tsx => id={"sometime}

2022-04-14 07:33 UTC, london-newyork requested changes
buttonの中にdivタグを入れているところがあり、そこだけ気になりましたが、いかがでしょう。

2022-04-14 07:33 UTC, london-newyork commented on src/components/btn/PlusBtn.tsx
>          <div className="box-border flex justify-center items-center w-[24px] h-[24px] bg-[#C2C6D2] rounded-full border-solid cursor-pointer">
buttonの中にdivを入れられるでしょうか？
 こちらによるとnot allowedとなります。
 https://validator.w3.org/

2022-04-14 07:33 UTC, london-newyork commented on src/components/btn/PlusBtn.tsx
>          <div className="box-border flex justify-center items-center w-[24px] h-[24px] bg-[#C2C6D2] rounded-full border-solid cursor-pointer">
入れ子ルールのサイトには入れられるとするところもありますが、この状態だと、コーダーから指摘を受けそうな感じがします。

2022-04-14 12:59 UTC, geyageya commented on src/components/btn/PlusBtn.tsx
>          <div className="box-border flex justify-center items-center w-[24px] h-[24px] bg-[#C2C6D2] rounded-full border-solid cursor-pointer">
以前、何かの折に、Eslintがでて、divにはonClickが使えないと書かれていたので、divをbuttonに変えた経緯があります。今日divにしても問題がなかったので、Divに変更します。

2022-04-15 12:25 UTC, london-newyork commented on src/components/Todo/TodoItem/TodoItem.tsx
> +              onClick={handleOnBlur}
了解です！

2022-04-15 12:28 UTC, london-newyork commented on src/components/btn/PlusBtn.tsx
>          <div className="box-border flex justify-center items-center w-[24px] h-[24px] bg-[#C2C6D2] rounded-full border-solid cursor-pointer">
私の伝え方がややこしくすみません。

`
<div>
<button>
<Image />
</button>
</div>
`

このような状態だったらOKかなと思いました。
ボタンは必要なのでむしろ使っていただきたいです。

2022-04-15 12:51 UTC, geyageya commented on src/components/btn/PlusBtn.tsx
>          <div className="box-border flex justify-center items-center w-[24px] h-[24px] bg-[#C2C6D2] rounded-full border-solid cursor-pointer">
昨晩、「指摘された２点修正」というファイルをアップしました。そこでは、buttonをやめて全てdivを使っています。
https://github.com/london-newyork/Qin_Todo_J2/pull/80/commits/2830093e56610f93ca9244b69e311d045922a5a1

先程、yururinさんが書かれていたように、buttonとdivを使って作ったところ、うまく作動しませんでした。なので、全てdivで行きたく思います。

2022-04-15 13:46 UTC, london-newyork requested changes

2022-04-15 13:46 UTC, london-newyork commented on src/components/btn/PlusBtn.tsx
>          <div className="box-border flex justify-center items-center w-[24px] h-[24px] bg-[#C2C6D2] rounded-full border-solid cursor-pointer">
試してみましたがこちらでしたら動くようです！

```
  return (
    <div>
      <div className="relative" >
        <button className="box-border flex justify-center items-center w-[24px] h-[24px] bg-[#C2C6D2] rounded-full border-solid cursor-pointer" onClick={props.onClick}>
          <Image alt="plus" src="/plus_icon.png" width="11px" height="11px" />
        </button>
      </div>
    </div>
  );
```

geyaさんのコードを確認したら、`<div .. onChange={props.onClick}>`となっていました。onChangeをonClickにして
`<div .. onClick={props.onClick}>`でも動きますが、やはりなんとなく違和感があり、、ここはbuttonの動きをするものでbuttonタグも使えますし、うーん`<button onClick={props.onClick}>`
としていただいたほうがいいかなと思います。

重箱の隅つつくようでしつこくすみません。
はじめに書いた一番上のコードを貼り付けていただければよいかと思います！

2022-04-15 14:24 UTC, london-newyork approved these changes
問題ないと思います、実装大変お疲れ様でした！

2022-04-15 14:26 UTC, london-newyork commented
![LGTM](https://images.lgtmgen.org/691e0d06-afe8-4615-8862-fb5cdf1f29c7)

2022-04-15 14:59 UTC, merged

2022-04-15 14:59 UTC, geyageya commented
１２週間ありがとうございました！マージして、明日にでもVercelにデプロイします。